reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session
  resources :subs
  resources :posts, except: [:index] do 
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create]
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint           not null, primary key
#  content           :text             not null
#  parent_comment_id :integer
#  user_id           :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ApplicationRecord
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord

  validates :title, presence: true
  # validates :subs, presence: { message: 'must have at least one sub' }

  belongs_to :author,
    foreign_key: :user_id,
    class_name: :User

  # belongs_to :sub  replaced by has many

  has_many :post_subs, inverse_of: :post, dependent: :destroy
  has_many :subs, through: :post_subs, source: :sub
end

reddit_clone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint           not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  validates :sub_id, uniqueness: { scope: :post_id }

  belongs_to :post
  belongs_to :sub

end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :description, :title, presence: true
  validates :title, uniqueness: true

  has_many :post_subs, inverse_of: :sub, dependent: :destroy
  has_many :posts, through: :post_subs, source: :post

  belongs_to :moderator,
    foreign_key: :user_id,
    class_name: :User

end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

  has_many :posts,
    foreign_key: :user_id,
    class_name: :Post

  has_many :subs,
    foreign_key: :user_id,
    class_name: :Sub 

  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil unless @user
    @user.is_password?(password) ? @user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout
    session[:session_token] = nil
    current_user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end


end

reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in

  def new
    debugger
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    debugger
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_url(@post)
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id, :parent_comment_id)
  end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def create
    # debugger
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.sub_id = params[:post][:sub_ids].first.to_i
    # ??? HOW TO GET SUB_ID

    if @post.save

      params[:post][:sub_ids].each do |sub|
        PostSub.create(post_id: @post.id, sub_id: sub)
      end

      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id], user_id: current_user.id)

  end

  def update
    @post = Post.find_by(id: params[:id], user_id: current_user.id)

    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.delete
    redirect_to subs_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id, sub_ids: [])
  end
  
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
      @user = User.new
      render :new
    end

    def create
      @user = User.find_by_credentials(
        params[:user][:username],
        params[:user][:password]
      )
      
      if @user
        login(@user)
        redirect_to subs_url
      else
        flash.now[:errors] = ["invalid credentials"]
        render :new
      end
    end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_logged_in

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
  end

  def update
    @sub = Sub.find_by(id: params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def index
    @subs = Sub.all
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
  
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
    
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/comments/new.html.erb
<h1>New Comment</h1>

<form action="<%= comments_url %>" method="post" > 
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
   <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">


  <label>Content:
    <textarea name="comment[content]"></textarea>
  </label>

  <br>

  <input type="submit" value="Create Comment">

  <br>
  
</form>  

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="post" > 
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 

  <label>Title:
    <input type="text" name="post[title]">
  </label>

  <label>URL:
    <input type="text" name="post[url]">
  </label>

  <label>Content:
    <textarea name="post[content]"></textarea>
  </label>

  <br>

  <input type="submit" value="Create Post">

  <br>

<label>Subs:
  <% Sub.all.each do |sub| %>
    <label>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"> 
      <%= sub.title %>
    </label>
    <br>
  <% end %>
</label>


  
</form>

reddit_clone/app/views/subs/index.html.erb
<h1>All Subs</h1>

<% @subs.each do |sub| %>
  <a href="<%=sub_url(sub)%>">  <%= sub.title %> </a>
<% end %>

<form action="<%=new_sub_url%>">
  <input type="submit" value="Create Sub">
</form>

reddit_clone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="post" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 

  <label>Title:
    <input type="text" name="sub[title]">
  </label>

  <label>Description:
    <input type="text" name="sub[description]">
  </label>

  <input type="submit" value="Create Sub">
</form>

reddit_clone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<a href="<%= new_post_url %>">Make New Post!</a> 

<ul>
  <% @sub.posts.each do |post| %>
      <li>
        <a href="<%= post_url(post) %>"> <%= post.title %> </a> 
      </li>
  <% end %>
</ul>

reddit_clone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post" > 
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 

  <label>Username:
    <input type="text" name="user[username]">
  </label>

  <label>Password:
    <input type="text" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>